# Generated by Django 5.0.2 on 2024-03-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='phonenumber',
        ),
    ]
